### ISSUE TITLE
vs2012 WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by walkwalkwalk** [frerich/clcache#24]
Hi,

I hvae 
           renamed cl.exe to cl_real.exe
           renamed cl.exe.config to cl_real.exe.config
           copied clcache.exe to cl.exe

 I have set the enviroment variable 
           CLCACHE_DIR = C:\clcache
           CLCACHE_CL = C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\cl_real.exe

Then i open Developer Command Prompt for VS2012 ,run cl , the output is 
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin>cl
Traceback (most recent call last):
  File "<string>", line 1094, in <module>
  File "<string>", line 996, in main
  File "<string>", line 1033, in processCompileRequest
  File "<string>", line 706, in invokeRealCompiler
  File "E:\PyInstaller-2.1\clcache\build\clcache\out00-PYZ.pyz\subprocess", line
 486, in call
  File "E:\PyInstaller-2.1\clcache\build\clcache\out00-PYZ.pyz\subprocess", line
 672, in __init__
  File "E:\PyInstaller-2.1\clcache\build\clcache\out00-PYZ.pyz\subprocess", line
 882, in _execute_child
WindowsError: [Error 5] Access is denied

Please help me to solve the problem....

**Comment by webmaster128** [comment]
knock knock, it this still active?

**Comment by frerich** [comment]
No activity in over two years, closing this.
