### ISSUE TITLE
clcache sometimes crash

### ISSUE THREAD

**Issue by sredouane** [frerich/clcache#25]
Hi,
i'm running clcache, most of time it does the job, but sometimes it just crash with this output:
Traceback (most recent call last):
  File "clcache.py", line 1093, in <module>
  File "clcache.py", line 995, in main
  File "clcache.py", line 1060, in processCompileRequest
  File "clcache.py", line 951, in processNoManifestMiss
  File "clcache.py", line 883, in addObjectToCache
  File "clcache.py", line 221, in setEntry
  File "clcache.py", line 88, in __enter__
  File "clcache.py", line 105, in acquire
__main__.ObjectCacheLockException: Error! WaitForSingleObject returns 258, last error 0

**Comment by tarcisiofischer** [comment]
It seems that we have a hard coded timeout here:
https://github.com/frerich/clcache/blob/master/clcache.py#L131

I'm unsure if this is causing the WAIT_TIMEOUT problem you reported, but I suggest making the ObjectCacheLock's 'timeoutMs' parameter to be overridable by a environment variable (defaults to 10 * 1000 as it is today).

**Comment by frerich** [comment]
Closed by pull request #34 .
