### ISSUE TITLE
Error installing latest on Windows 10

### ISSUE THREAD

**Issue by chahn1138** [frerich/clcache#344]
Hello,

I am trying to manually execute a process that I stole from a Jenkins Project...it build and packages up clcache for its incorporation into another product.

But "%PYTHON_SCRIPTS%\pyinstaller clcache.py"  runs into an exception:

C:\Users\chahn\issues\ES-13600 - Mystery windows build failures\github\clcache-tip>**pyinstaller clcache.py**
396 INFO: PyInstaller: 3.4
396 INFO: Python: 3.7.0
402 INFO: Platform: Windows-10-10.0.17134-SP0
404 INFO: wrote C:\Users\chahn\issues\ES-13600 - Mystery windows build failures\github\clcache-tip\clcache.spec
410 INFO: UPX is not available.
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python37\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 189, in __init__
    raise ValueError("script '%s' not found" % script)
**ValueError: script 'C:\Users\chahn\issues\ES-13600 - Mystery windows build failures\github\clcache-tip\clcache.py' not found**

Not much to work with but this is all I have at this juncture....

I saw that someone else here saw the same but got no responses...I will continue my search...

**Comment by chahn1138** [comment]
OK....tried to bold two strings....messed the whole thing up...

**Comment by izmmisha** [comment]
You should use `pyinstaller/clcache_main.py` script instead `clcache.py` with pyinstaller

**Comment by chahn1138** [comment]
Thank you for the time!

I tried that but got no further:

chahn@D6KZW182 MINGW64 ~/issues/ES-13600 - Mystery windows build failures/github/clcache-tip (master)
$ pyinstaller ./pyinstaller/clcache_main.spec
453 INFO: PyInstaller: 3.4
453 INFO: Python: 3.7.0
453 INFO: Platform: Windows-10-10.0.17134-SP0
459 INFO: UPX is not available.
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python37\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python37\lib\site-packages\PyInstaller\building\build_main.py", line 782, in build
    with open(spec, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: './pyinstaller/clcache_main.spec'

The file is just a wrapper of sorts:

chahn@D6KZW182 MINGW64 ~/issues/ES-13600 - Mystery windows build failures/github/clcache-tip (master)
$ cat pyinstaller/clcache_main.py
from clcache.__main__ import main
main()

Did I misunderstand your suggestion?

**Comment by izmmisha** [comment]
Well, I see from your comment `pyinstaller ./pyinstaller/clcache_main.spec` not the `pyinstaller/clcache_main.py`

As result you get again `FileNotFoundError: [Errno 2] No such file or directory: './pyinstaller/clcache_main.spec'`

**Comment by chahn1138** [comment]
Well, you are right.....could have sworn that shell-auto-complete made that name but the corrected name did execute to completion.  I will close this.  Thank you for the kick I seem to have needed!
